[package]
name = "chariot_core"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chariot_runtime.workspace = true
chariot_rootfs.workspace = true
chariot_util.workspace = true
nix = { workspace = true, features = ["fs"] }
thiserror.workspace = true
xxhash-rust.workspace = true
rusqlite.workspace = true
