[package]
name = "chariot_rootfs"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chariot_runtime.workspace = true
chariot_util.workspace = true
hex = "0.4.3"
reqwest = { version = "0.13.2", features = ["blocking"] }
rusqlite.workspace = true
serde = { workspace = true, features = ["derive"] }
sha2 = "0.11.0"
tar = "0.4.45"
thiserror.workspace = true
toml.workspace = true
url = "2.5.8"
xz2 = "0.1.7"
zstd = "0.13.3"
